---
apps:
- name: billing-app
  token: <papertrail-app-token>
  events:
  - query: redis-connect-error
    size: 10
  - query: fetch-error
    size: 5
    color: teal
- name: invoicing-app
  token: <papertrail-app-token>
  events:
  - query: GET /invoices timeout
    size: 1
    color: blue
