---
apps:
- name: bitpaper-ws
  token: BITPAPER_WS_PAPERTRAIL_API_TOKEN
  events:
  - query: Relocating dyno to a new server
    color: cyan
    size: 8
  - query: Process exited with status
    size: 2
  - query: SocketClosedUnexpectedlyError
    size: 10
    color: red
  - query: fetchSockets response
    size: 2
- name: bitpaper-api
  token: BITPAPER_API_PAPERTRAIL_API_TOKEN
  events:
  - query: ping timeout
    size: 2
    color: blue
  - query: websocket error
    size: 2
    color: magenta
  - query: transport close
    size: 2
    color: black
