---
apps:
- name: bitpaper-ws
  token: BITPAPER_WS_PAPERTRAIL_API_TOKEN
  events:
  - query: Relocating dyno to a new server
    color: cyan
    size: 10
  - query: crashing
    size: 5
    color: red
  - query: fetchSockets response
    size: 2
  - query: starting to up
    size: 8
    color: pink
- name: bitpaper-api
  token: BITPAPER_API_PAPERTRAIL_API_TOKEN
  events:
  - query: ping timeout
    size: 2
    color: blue
  - query: websocket error
    size: 2
    color: magenta
  - query: transport close
    size: 2
    color: black
